name: Duyuru Kontrol

on:
  schedule:
    - cron: "*/10 * * * *"   # Her 10 dakikada bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Scripti çalıştır
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        run: python main.py

      - name: Değişiklikleri commit et ve pushla
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add son_duyuru.txt
          git commit -m "Update son_duyuru.txt [skip ci]" || echo "No changes to commit"
          git push
