name: Duyuru Kontrol

on:
  schedule:
    - cron: "*/1 * * * *"   # Her 15 dakikada bir çalışır (UTC zamanına göre)
  workflow_dispatch:         # Manuel çalıştırma butonu da ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Scripti çalıştır
        run: |
          python main.py
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "crongenerated"
          git push

