name: Duyuru Kontrol

on:
  schedule:
    - cron: "*/1 * * * *"   # Her 15 dakikada bir
  workflow_dispatch:         # Elle başlatma için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Cache son_duyuru.txt
        uses: actions/cache@v3
        with:
          path: son_duyuru.txt
          key: duyuru-cache

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Scripti çalıştır
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        run: python main.py
